[tool.poetry]
name = "blog-spark"
version = "0.1.0"
description = ""
authors = ["Zackary Luedtke <luedtkezack@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyspark = "3.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
