SELECT COUNT(*)
FROM gold.blog_activity
UNION ALL
SELECT COUNT(*)
FROM gold.blogs
UNION ALL
SELECT COUNT(*)
FROM gold.comments
UNION ALL
SELECT COUNT(*)
FROM gold.favorites
UNION ALL
SELECT COUNT(*)
FROM gold.opinions
UNION ALL
SELECT COUNT(*)
FROM gold.tag_lookup
UNION ALL
SELECT COUNT(*)
FROM gold.users;
