@startuml

skinparam linetype ortho

entity "users" as users {
  *user_id : INT <<PK>>
  --
  first_name : VARCHAR(50)
  last_name : VARCHAR(50)
  email : VARCHAR(150)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "blogs" as blogs {
  *blog_id : INT <<PK>>
  --
  *user_id : INT <<FK>>
  blog_title : VARCHAR(150)
  blog_content : TEXT
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "comments" as comments {
  *comment_id : INT <<PK>>
  --
  *blog_id : INT <<FK>>
  *user_id : INT <<FK>>
  content : TEXT
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "favorites" as favorites {
  *favorite_id : INT <<PK>>
  --
  *blog_id : INT <<FK>>
  *user_id : INT <<FK>>
  favorite_date : DATE
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "blog_opinions" as blog_opinions {
  *opinion_id : INT <<PK>>
  --
  *blog_id : INT <<FK>>
  *user_id : INT <<FK>>
  opinion : BOOLEAN
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "tags" as tags {
  *tag_id : INT <<PK>>
  --
  name: VARCHAR(50)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "blog_tags" as blog_tags {
  *tag_id : INT <<FK>>
  *blog_id : INT <<FK>>
}

users ||..o{ blogs
users ||..o{ comments
blogs ||..o{ comments
users ||..o{ favorites
blogs ||..o{ favorites
users ||..o{ blog_opinions
blogs ||..o{ blog_opinions
tags ||..o{ blog_tags
blogs ||..o{ blog_tags

@enduml